/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/zekailin00/Desktop/PhysX/physx/snippets/snippethelloworld/lf-port/Hello.lf
 */

#include "reactor-cpp/reactor-cpp.hh"

#include "Hello/_lf_preamble.hh"

using namespace std::chrono_literals;
using namespace reactor::operators;

            
